# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the gatsby branch
  push:
    branches: [ gatsby ]
  pull_request:
    branches: [ gatsby ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: npm install -g yarn
      - run: npm install -g gatsby-cli
      - uses: actions/checkout@v2
        with:
          repository: gongbaodd/blog.gongbushang.com
          path: generator
      - run: cd generator
      - run: yarn
      - run: yarn build
      - run: yarn cp:cname
      - run: cd ..
      - name: Deploy ðŸš€
        uses: crazy-max/ghaction-github-pages@v2
          target_branch: gh-pages
          build_dir: public
        GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}